### ISSUE TITLE
Xamarin essentials 1.3.1 Azure Pipeline Failure for both iOS and Android (Advice required)

### ISSUE THREAD

**Issue by developer9969** [xamarin/Essentials#910]
### Steps to Reproduce

1. Update your project to use xamarin.essentials 1.31 this references android 28.0.0.3
2. Run your iOS and Android pipeline and it will error

Could you please advice which version of mono we should use? 

Can we use the Boot Task? Never used , may be I should 

Those Hosted Agent I guess are out of date.

Error below
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2129,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Stack`1' (defined in assembly 'Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Stack`1

**Comment by vladrudych** [comment]
I've resolved the same issue upgrading SDK version in Build Configuration to Latest stable (Xamarin Android 9.4, Mono 6.0)

**Comment by marza91** [comment]
Managed to get it working for Android, but not iOS:
- Set vmImage to windows-2019 (or windows-latest)
- In the XamarinAndroid@1 task:
      msbuildArguments: '/p:AndroidNdkDirectory=$(ANDROID_NDK_HOME)'
      jdkVersionOption: 1.8

The latest step was required for me because I got an error about missing java sdk. See this [link](https://github.com/microsoft/azure-pipelines-image-generation/blob/91fcf62e28a7e05686b780f78a890598a8a60483/images/win/Vs2019-Server2019-Readme.md#known-issues)

I'm working on figuring this out for Mac/Xamarin.iOS as well, currently looking into [this](https://github.com/MicrosoftDocs/vsts-docs/issues/2129)

Not sure if this is directly related to Xamarin Essentialt, or just the Microsoft build servers being outdated.

**Comment by developer9969** [comment]
Has anyone made it work on iOS? We cannot release a fix to a client if we cannot build.
Really grateful for any input or suggestion

**Comment by developer9969** [comment]
Running below bash script in iOS azure pipeline but does not work. checked the pipeline pool information  and it has:

Visual Studio for Mac: 8.3.0.1805
Mono Version: 5.4.0
Mono Version: 6.0.0
Mono Version: 5.0.1
Mono Version: 5.4.1
Mono Version: 6.4.0
etc....



tried below script  with "6_0_0"  "6_0_0_0"  "6_4_0_0"  

> monoVersion=$1

#!/bin/bash
echo "Setting mono version to monoVersion" 
echo $monoVersion

sudo xcodebuild -showsdks

SYMLINK=monoVersion
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh monoVersion


Get error cannot find mono version if i set it to  5_16_0_0 i get a different error.

anybody???
thanks

**Comment by jamesmontemagno** [comment]
You could give boots a try: https://github.com/jonathanpeppers/boots#some-examples

Be sure to install .NET Core 2.2 as the first step. Seems like you have some sorta missmatch on the build agent. They recently updated items. 

6.4.0 is the current mono build.

**Comment by marza91** [comment]
@developer9969 Sorry to say, I haven't been able to resolve this myself. But if building and/or publishing this is your most urgent issue, are you not able to create a build and publish it manually on your own machine? For me this is mostly an annoyance at the moment as I can build and create ipa/apk files manually as a fallback.

Regarding .Net Core, I am running version 3.0 locally and the latest build agents are already running 2.2 (I think). So I'm also trying to figure out how to use boots to upgrade to 3.0. So far I've got this in my yaml-file, wich seems to be running just fine (You have to install the boots extension for Azure Devops: https://marketplace.visualstudio.com/items?itemName=pjcollins.azp-utilities-boots )

```
  - task: Boots@1
    displayName: Install Dotnet core
    inputs:
      uri: https://download.visualstudio.microsoft.com/download/pr/5c281f95-91c4-499d-baa2-31fec919047a/38c6964d72438ac30032bce516b655d9/dotnet-sdk-3.0.100-osx-x64.pkg
```
Only thing missing for me now (hopefully) is to convince the Mac agent to actually use the newer version..

**Comment by marza91** [comment]
@developer9969
I got the build working! I still haven't tested if this will run on a device, and I have not added Xamarin.Essentials back in, but the build is working with .Net Core 3.0, Xcode 11 and Xamarin.iOS 13. Didn't end up having to use boots at all, but the "UseDotNet@2" task ([doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)). My full ios build yaml:

```
trigger:
- master
jobs:
- job: iOS
  pool:
    vmImage: 'macOS-10.14'
  variables:
    buildConfiguration: 'Release'
    group: [redacted]-build
  steps:

  - task: UseDotNet@2
    displayName: 'Select .Net Core version'
    inputs:
      packageType: sdk
      version: 3.0.100
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_4_0
    displayName: 'Select Xamarin version'
  - script: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_11.app;sudo xcode-select --switch /Applications/Xcode_11.app/Contents/Developer
    displayName: 'Select Xcode version'
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'deploycert.p12'
      certPwd: '$(apple-cert-key)'
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '[redacted]'
  - task: XamariniOS@2
    inputs:
      solutionFile: '[redacted].iOS.csproj'
      configuration: '$(buildConfiguration)'
      packageApp: true
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
```

I just removed some of our product names from it (replaced with "[redacted]"), should be quite easy to figure out. Hope this solves the issue for you as well!

**Comment by developer9969** [comment]
@marza91 hi thanks for the update .  I had to revert my code and remove reference to latest xamarin.essentials and latest xamarin forms (for now). We will delay a particular functionality. 

My build is a bit more involved but the core bits are the same I guess. One question Why do we need .net core? Would it have worked without?

**Comment by marza91** [comment]
I have very little knowledge about .Net versions unfortunately, but I believe that .Net Core is what's used to build projects targeting .Net Standard for iOS/Mac. I have both some .Net Standard (class libraries) and .Net Core projects (Nunit tests) in my solution, and without .Net Core 3.0 none of them would build at all. I think maybe the same goes for the Xamarin.Forms and/or the Xamarin.iOS project, but as I said I know very little about how this works :sweat_smile:

**Comment by LanceMcCarthy** [comment]
I've been trying to fix this for several days myself. Let me share what I've discovered and what I did to temporarily resolve it:

It seems that the [macos-latest agent](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xamarin) (macos-10.14) already has everything installed and is up to date. I’ve painstakingly checked the listed versions against what I’m building with locally.

•	Xamarin.iOS [is listed as 13.2.042](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xamarinios-sdk)
•	Xamarin.Android [is listed as 10.0.0.43](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xamarinandroid-sdk)
•	Mono [is listed as 6.4.0](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#mono)

It seems that what is installed locally is identical:

![image](https://user-images.githubusercontent.com/3520532/66005828-9648b080-e47a-11e9-85be-2a94c7b92ac6.png)

I'm waiting for more feedback from Xamarin team members to see if they can investigate this as well. I seriously double this is a Xamarin.Essential problems, these error happen when the SDK are not lined up. 

### Temporary solution

I was able to fix my builds by dropping my project’s iOS target to **12.0**, and manually set the Mono version to **1.58.1**.

![image](https://user-images.githubusercontent.com/3520532/66005840-a1034580-e47a-11e9-8acf-d49fe426fb62.png)

Here's the copyable YAML

```yaml
  - task: Bash@3
    displayName: 'Set Mono Version'
    inputs:
      targetType: 'inline'
      script: |
        SYMLINK=5_18_1
        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

  - task: Bash@3
    displayName: 'Select Xamarin SDK version'
    inputs:
      targetType: 'inline'
      script: |
        /bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1"
```
